### ISSUE TITLE
Diseño arquitectura de sistema

### ISSUE THREAD

**Issue by aliciafdezc** [Alextorres20/Desafio2-Back-Laravel#1]
- [x] Diseño de BD
- [x]  Creación de Repositorios
- [x] Wireframes
- [x]  Proyectos base de back y front

**Comment by Alextorres20** [comment]
Alicia acabo de subir la Estructura de la BD en el github. Y ademas he añadido un SQL que se llama "Desafio2Estructurada.sql". Por si lo quieres probarlo en tu PC
