### ISSUE TITLE
[DIOS] Crear humano ( 7 )

### ISSUE THREAD

**Issue by aliciafdezc** [Alextorres20/Desafio2-Back-Laravel#3]
Interfaces ( 1 )
- [x] Inputs para correo, email, contraseña

Cliente ( 1 )
- [x] Validar usuario

Servidor ( 5 )
- [x] Guardar humano
- [x]  Validar usuario
- [x] Generar de forma aleatoria sus caracteristicas
- [x] Asignar dios a humano
- [x] Activar usuari automáticamente

**Comment by Alextorres20** [comment]
Finalizacion Oficial de Creacion de USUARIOS como dios
