### ISSUE TITLE
[HUMANO] Registro en el sistema para conocer mi destino ( 9 )

### ISSUE THREAD

**Issue by aliciafdezc** [Alextorres20/Desafio2-Back-Laravel#5]
Interfaces ( 1 )

- [x] Input para nombre, correo y contraseña

Cliente ( 1 )

- [x] Check de correo y contraseña

Servidor ( 7 )

- [x]  Validar usuario
- [x]  Registrar usuario
- [x]  Generar de forma aleatoria sus caracteristicas
- [x]  Asignar dios a humano

**Comment by Alextorres20** [comment]
Alicia yo por mi ya he finalizado esta Issue. Si quieres echarle un vistazo.
